Lesson4prj/urls.py
from django.contrib import admin
from django.urls import path
from less4App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('create', views.create),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
    path('send',views.email,name='send'),
    # path('email/', views.emailView, name='email'),
    # path('success/', views.successView, name='success'),
]

less4App/models.py
from django.db import models

from datetime import datetime

class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Employee Name", max_length=100)
    email = models.EmailField("Email Address", max_length=100)
    # dob = models.DateTimeField("Date of Birth",default=datetime.now, blank=True,help_text="Format: yyyy/mm/dd")
    dob = models.DateTimeField("Date of Birth",help_text="Format: yyyy/mm/dd")
    salary = models.FloatField("Monthly Salary")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "employees"

less4App/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

        widgets = {
                'dob'   : forms.DateInput(attrs={'class': 'form-control datepicker1'}),
                'name'  : forms.TextInput(attrs={'class': 'form-control'}),
                'email' : forms.TextInput(attrs={'class': 'form-control','placeholder': 'Email Address'}),
                'salary': forms.TextInput(attrs={'class': 'form-control'}),

    	}

        dob = forms.DateField(
            widget=forms.DateInput(format='%Y/%m/%d'),input_formats=('%Y/%m/%d', )
        )

class ContactForm(forms.Form):
        to      = forms.EmailField(required=True,widget= forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder':'Email Address'}))
        subject = forms.CharField( required=True,widget= forms.TextInput(attrs={'class': 'form-control col-sm-4','placeholder':'Subject'}))
        message = forms.CharField( required=True,widget= forms.Textarea(attrs={'class': 'form-control col-sm-4','placeholder':'Message'}), label=(''))

less4App/views.py
from django.shortcuts import render, redirect
from .models import Employee
from less4App.forms import EmployeeForm

from django.core.paginator import Paginator
from django.contrib import messages

from django.core.mail import send_mail
from django.core.mail import BadHeaderError
from django.conf import settings

from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from less4App.forms import ContactForm

# Create your views here.
def index(request):
    emp = Employee.objects.all()

    context = {'title': 'Welcome', 'employees': emp}
    return render(request, 'index.html', context)

def create(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.error(request,'Insert successfully ')
                return redirect('/')
            except Exception as e:
                print("type error: " + str(e))
        else:
            pass
    else:
        form = EmployeeForm()
    return render(request,'create.html',{'form':form})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,request.FILES) #try
    return render(request,'edit.html',{'employee':employee,'form':form})

def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,request.FILES,instance=employee)
    if form.is_valid():
        try:
            form.save()
            messages.error(request,'Update successfully ')
            return redirect('/')
        except Exception as e:
                print("type error: " + str(e))
    else:
        messages.error(request,form.errors)

    return render(request, 'edit.html', {'employee': employee,'form':form})

def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/')


def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['to']
            message = form.cleaned_data['message']

            recipient_list = []
            recipient_list.append(from_email)
            try:
                emailobj = EmailMessage(subject, message, to=recipient_list)
                emailobj.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')
    return render(request, "email.html", {'form': form})

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['to']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['nazmul@daffodil.ac'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "email.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message. 2')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>

   <title>{% block title %}Title{% endblock %}</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

   <script type="text/javascript" src="{% static 'js/app.js' %}" ></script>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.18/datatables.min.css"/>
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.18/datatables.min.js"></script>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

    {% block stylesheet %}{% endblock %}
  </head>
<body>
  <header>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h1>
            <a href="">
              <img src="{% static 'images/logo.png' %}" alt="No Image" class="logo" width=100%>
            </a>
          </h1>
        </div>
        <div class="col-sm-8">
        </div>
      </div>
    </div>
  </header>
  <nav class="menu">
    <div class="container">
      <a href="/">Home</a> |
      <a href="/create">Add New Record</a>
    </div>
  </nav>
  <br><br>
  <main>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </main>


  <script>
    $(function () {

    });

    $(function() {
      $('#emptable').DataTable({
        "dom": '<f<t>ip>',
        "lengthMenu": [[5,10, 25, 50, -1], [5,10, 25, 50, "All"]]

      });
  } );

  $(document).ready(function() {
        $( ".datepicker1" ).datepicker({
        format: "mm/dd/yyyy",
      weekStart: 0,
      calendarWeeks: true,
      autoclose: true,
      todayHighlight: true,
      rtl: true,
      orientation: "auto"
      });
      } );

      function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
                  reader.onload = function (e) {
                      $('.blah')
                          .attr('src', e.target.result).width(300);
                  };
                  reader.readAsDataURL(input.files[0]);
        }
      }
  </script>
  {% block javascript %}{% endblock %}
</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}
{% block content %}

<!-- <form method="POST" class="post-form" action="/create" enctype="multipart/form-data"> -->
<form method="POST" class="post-form" enctype="multipart/form-data">
{% csrf_token %}
{{ form.non_field_errors }}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field.errors }}
  {{ hidden_field }}
{% endfor %}

<table>
  {% for field in form.visible_fields %}
    <tr>
      <th>{{ field.label_tag }}</th>
      <td>
        {{ field.errors }}
        {{ field }}
        {{ field.help_text }}
      </td>
    </tr>
  {% endfor %}
</table>
       <button type="submit">Submit</button>
</form>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock %}
{% block stylesheet %}  {% endblock %}
{% block content %}
    <form method="POST" class="post-form" action="/update/{{employee.id}}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
          <!-- {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %} -->

        {% for message in messages %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message }}
            </div>
        {% endfor %}
        <br>


        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <h3>Edit Employee</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">employee Id:</label>
        <div class="col-sm-4">
            <input type="text" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          <input type="text" name="name" id="id_name" required maxlength="20" value="{{ employee.name | upper }}"/>
        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          <input type="text" name="email" id="id_email" required maxlength="20" value="{{ employee.email }}"/>

        </div>
      </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Date of birth:</label>
        <div class="col-sm-4">
          <input type="text" name="dob" id="id_dob" required maxlength="20" value="{{ employee.dob | date:"m/d/Y"  }}"/>
        </div>
      </div>
      <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Salary:</label>
    <div class="col-sm-4">
      <input type="text" name="salary" id="id_salary" required maxlength="20" value="{{ employee.salary |floatformat:"-3"}}"/>
    </div>

  </div>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
        </div>
    </form>
{% endblock %}

templates/email.html
{% extends 'base.html' %}
{% block title %}Email{% endblock %}
{% block content %}
<h1>Contact Us</h1>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group row">
            {{ field.errors }}
            <label class="col-sm-2 col-form-label" for="{{ field.name }}">{{ field.label_tag }}</label>
            {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
    <div class="">
      {% for message in messages %}
          <div class="alert alert-danger">
              <a class="close" href="#" data-dismiss="alert">×</a>
              {{ message }}
          </div>
      {% endfor %}
      <br>

      <center><a href="/create" class="btn btn-primary">Add New Record</a></center>
      <br><br>
    </div>
    <table class="table table-bordered" id="emptable" data-page-length='5'>
      <thead class="thead-dark">
        <tr>
          <td>Id</td>
          <td>Name</td>
          <td>Email</td>
          <td>Actions</td>
        </tr>
      </thead>
      <tbody>
        {% for emp in employees %}
        <tr>
          <td>{{emp.id}}</td>
          <td>{{emp.name | upper }}</td>
          <td>{{emp.email}}</td>
          <td>
                <a href="/edit/{{ emp.id }}">Edit</a>
                <a href="/delete/{{ emp.id }}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

<br>
{% endblock %}